/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Entidades.AlquilerPelicula;
import Mantenimientos.MantenimientoAlquilerPelicula;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


public class FrmAquilerPelicula extends javax.swing.JFrame {

    MantenimientoAlquilerPelicula mantenimiento = new MantenimientoAlquilerPelicula();
    
    public FrmAquilerPelicula() {
        initComponents();
        mantenimiento.ListadoAlquilerPelicula();
        
        if (mantenimiento.ListadoAlquilerPelicula().size() <= 0)
        {
            FiltrobtnBusqueda.setEnabled(false);
        }
        else
        {
            FiltrobtnBusqueda.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabControl = new javax.swing.JTabbedPane();
        PnlFilter = new javax.swing.JPanel();
        FiltroCodigoPelicula = new javax.swing.JLabel();
        FiltroCodigoAlquiler = new javax.swing.JLabel();
        FiltroFechaAlquiler = new javax.swing.JLabel();
        FiltrotxtCodigo = new javax.swing.JTextField();
        FiltrotxtNombre = new javax.swing.JTextField();
        FiltrotxtEstado = new javax.swing.JTextField();
        FiltrobtnBusqueda = new javax.swing.JButton();
        FiltrobtnAgregar = new javax.swing.JButton();
        PnlMantenimiento = new javax.swing.JPanel();
        MantenimientoCodigoAlquiler = new javax.swing.JLabel();
        MantenimientoCodigoPelicula = new javax.swing.JLabel();
        MantenimientoFechaAlquiler = new javax.swing.JLabel();
        MantenimientoAlquilada = new javax.swing.JLabel();
        MantenimientotxtCodigoAlquiler = new javax.swing.JTextField();
        MantenimientotxtCodigoPelicula = new javax.swing.JTextField();
        MantenimientotxtFechaAlquiler = new javax.swing.JTextField();
        MantenimientotxtAlquilada = new javax.swing.JTextField();
        MantenimientobtnGuardar = new javax.swing.JButton();
        MantenimientoEstado1 = new javax.swing.JLabel();
        MantenimientoEstado = new javax.swing.JLabel();
        MantenimientotxtEstado = new javax.swing.JTextField();
        MantenimientobtnCancelar = new javax.swing.JButton();
        PnlResultado = new javax.swing.JPanel();
        ResultadotblListaScrl = new javax.swing.JScrollPane();
        ResultadotblLista = new javax.swing.JTable();
        GeneroTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        FiltroCodigoPelicula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FiltroCodigoPelicula.setText("Codigo Pelicula");

        FiltroCodigoAlquiler.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FiltroCodigoAlquiler.setText("Codigo Alquiler");

        FiltroFechaAlquiler.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FiltroFechaAlquiler.setText("Fecha de alquiler");

        FiltrobtnBusqueda.setText("Busqueda");

        FiltrobtnAgregar.setText("Agregar");
        FiltrobtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FiltrobtnAgregarMouseClicked(evt);
            }
        });
        FiltrobtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltrobtnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlFilterLayout = new javax.swing.GroupLayout(PnlFilter);
        PnlFilter.setLayout(PnlFilterLayout);
        PnlFilterLayout.setHorizontalGroup(
            PnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FiltroCodigoAlquiler)
                    .addComponent(FiltroFechaAlquiler)
                    .addComponent(FiltroCodigoPelicula))
                .addGap(18, 18, 18)
                .addGroup(PnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FiltrotxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(FiltrotxtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addComponent(FiltrotxtEstado)))
                .addGap(60, 60, 60)
                .addGroup(PnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FiltrobtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FiltrobtnBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        PnlFilterLayout.setVerticalGroup(
            PnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFilterLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FiltroCodigoAlquiler)
                    .addComponent(FiltrotxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FiltrobtnBusqueda))
                .addGap(17, 17, 17)
                .addGroup(PnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FiltroCodigoPelicula)
                    .addComponent(FiltrotxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FiltrobtnAgregar))
                .addGap(18, 18, 18)
                .addGroup(PnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FiltroFechaAlquiler)
                    .addComponent(FiltrotxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        TabControl.addTab("Filtro", PnlFilter);

        PnlMantenimiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        MantenimientoCodigoAlquiler.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MantenimientoCodigoAlquiler.setText("Codigo Alquiler");

        MantenimientoCodigoPelicula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MantenimientoCodigoPelicula.setText("Codigo Pelicula");

        MantenimientoFechaAlquiler.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MantenimientoFechaAlquiler.setText("Fecha de alquiler");

        MantenimientoAlquilada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MantenimientoAlquilada.setText("Alquilada");

        MantenimientotxtCodigoAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantenimientotxtCodigoAlquilerActionPerformed(evt);
            }
        });

        MantenimientobtnGuardar.setText("Guardar");
        MantenimientobtnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MantenimientobtnGuardarMouseClicked(evt);
            }
        });

        MantenimientoEstado1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        MantenimientoEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MantenimientoEstado.setText("Estado");

        MantenimientobtnCancelar.setText("Cancelar");
        MantenimientobtnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MantenimientobtnCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PnlMantenimientoLayout = new javax.swing.GroupLayout(PnlMantenimiento);
        PnlMantenimiento.setLayout(PnlMantenimientoLayout);
        PnlMantenimientoLayout.setHorizontalGroup(
            PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlMantenimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlMantenimientoLayout.createSequentialGroup()
                        .addComponent(MantenimientoAlquilada)
                        .addGap(18, 18, 18)
                        .addComponent(MantenimientotxtAlquilada, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(MantenimientoEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MantenimientotxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlMantenimientoLayout.createSequentialGroup()
                        .addGroup(PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MantenimientoCodigoAlquiler)
                            .addComponent(MantenimientoCodigoPelicula)
                            .addComponent(MantenimientoFechaAlquiler))
                        .addGap(45, 45, 45)
                        .addGroup(PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MantenimientotxtFechaAlquiler)
                            .addComponent(MantenimientotxtCodigoPelicula)
                            .addComponent(MantenimientotxtCodigoAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MantenimientobtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MantenimientobtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PnlMantenimientoLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(MantenimientoEstado1)
                    .addContainerGap(466, Short.MAX_VALUE)))
        );
        PnlMantenimientoLayout.setVerticalGroup(
            PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlMantenimientoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MantenimientoCodigoAlquiler)
                    .addComponent(MantenimientotxtCodigoAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MantenimientobtnGuardar))
                .addGap(17, 17, 17)
                .addGroup(PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MantenimientoCodigoPelicula)
                    .addComponent(MantenimientotxtCodigoPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MantenimientobtnCancelar))
                .addGap(18, 18, 18)
                .addGroup(PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MantenimientoFechaAlquiler)
                    .addComponent(MantenimientotxtFechaAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MantenimientoAlquilada)
                    .addComponent(MantenimientotxtAlquilada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MantenimientoEstado)
                    .addComponent(MantenimientotxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlMantenimientoLayout.createSequentialGroup()
                    .addContainerGap(162, Short.MAX_VALUE)
                    .addComponent(MantenimientoEstado1)
                    .addGap(147, 147, 147)))
        );

        TabControl.addTab("Mantenimiento", PnlMantenimiento);

        ResultadotblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ResultadotblListaScrl.setViewportView(ResultadotblLista);

        javax.swing.GroupLayout PnlResultadoLayout = new javax.swing.GroupLayout(PnlResultado);
        PnlResultado.setLayout(PnlResultadoLayout);
        PnlResultadoLayout.setHorizontalGroup(
            PnlResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ResultadotblListaScrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        PnlResultadoLayout.setVerticalGroup(
            PnlResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlResultadoLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(ResultadotblListaScrl, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        TabControl.addTab("Resultado", PnlResultado);

        GeneroTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        GeneroTitulo.setText("Mantenimiento Alquiler Pelicula");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TabControl, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GeneroTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(GeneroTitulo)
                .addGap(18, 18, 18)
                .addComponent(TabControl)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MantenimientotxtCodigoAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantenimientotxtCodigoAlquilerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MantenimientotxtCodigoAlquilerActionPerformed

    private void FiltrobtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltrobtnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FiltrobtnAgregarActionPerformed

    private void MantenimientobtnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MantenimientobtnCancelarMouseClicked
        TabControl.setEnabledAt(0,true);
        TabControl.setEnabledAt(1,false);
        TabControl.setSelectedIndex(0);
        LimpiarObjetos();
    }//GEN-LAST:event_MantenimientobtnCancelarMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        TabControl.setEnabledAt(1,false);
        TabControl.setEnabledAt(2,false);
    }//GEN-LAST:event_formWindowOpened

    private void FiltrobtnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FiltrobtnAgregarMouseClicked
        TabControl.setEnabledAt(0,false);
        TabControl.setEnabledAt(1,true);
        TabControl.setSelectedIndex(1);
        LimpiarObjetos();
    }//GEN-LAST:event_FiltrobtnAgregarMouseClicked

    private void MantenimientobtnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MantenimientobtnGuardarMouseClicked
        int CodigoAlquiler = 0;
        int CodigoPelicula = 0;
        
        if (!MantenimientotxtCodigoAlquiler.getText().equals(""))
        {
            CodigoAlquiler = Integer.parseInt(MantenimientotxtCodigoAlquiler.getText());
            CodigoPelicula = Integer.parseInt(MantenimientotxtCodigoPelicula.getText());
            
                
            AlquilerPelicula alquilerpelicula = new AlquilerPelicula (
                    CodigoAlquiler,
                    CodigoPelicula,
                    MantenimientotxtFechaAlquiler.getText(),
                    true,  
                    MantenimientotxtEstado.getText());

            mantenimiento.AddElemento(alquilerpelicula);
            
            ShowTable();
            TabControl.setEnabledAt(0,true);
            TabControl.setEnabledAt(2,true);
            TabControl.setEnabledAt(1,false);
            TabControl.setSelectedIndex(0);
            LimpiarObjetos();
         }
    }//GEN-LAST:event_MantenimientobtnGuardarMouseClicked

    public void LimpiarObjetos()
    {
        FiltrotxtCodigo.setText("");
        FiltrotxtEstado.setText("");
        FiltrotxtNombre.setText("");
        MantenimientotxtCodigoAlquiler.setText("");
        MantenimientotxtCodigoPelicula.setText("");
        MantenimientotxtFechaAlquiler.setText("");
        MantenimientotxtAlquilada.setText("");
        MantenimientotxtEstado.setText("");
    }
    /**
     * @param args the command line arguments
     */  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAquilerPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAquilerPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAquilerPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAquilerPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAquilerPelicula().setVisible(true);
            }
        });
    }

    private void ShowTable()
    {
        ArrayList<AlquilerPelicula> lista = mantenimiento.ListadoAlquilerPelicula();
        
        String[] columnNames = {"Codigo Alquiler","Codigo Pelicula","Fecha Alquiler","Alquilada","Estado"};
        DefaultTableModel model = new DefaultTableModel ();
        
        model.setColumnIdentifiers (columnNames);
        
        ResultadotblLista.setModel (model);
        
        ResultadotblLista.setForeground(Color.BLACK);
        Font font = new Font ("",1,12);
        ResultadotblLista.setFont(font);
        ResultadotblLista.setRowHeight (30);
        
        for (int i = 0; i < lista.size(); i++)
        {
            int CodigoAlquiler = lista.get(i).getCodigoAlquiler();
            int CodigoPelicula = lista.get(i).getCodigoPelicula();
            String FechaAlquiler = lista.get(i).getFechaAlquiler();
            Boolean Alquilada = lista.get(i).getAlquilada();
            String Estado = lista.get(i).getEstado();
            
            Object[] data = {CodigoAlquiler,CodigoPelicula,FechaAlquiler,Alquilada,Estado};
            
            model.addRow(data);           
        }        
    }  
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FiltroCodigoAlquiler;
    private javax.swing.JLabel FiltroCodigoPelicula;
    private javax.swing.JLabel FiltroFechaAlquiler;
    private javax.swing.JButton FiltrobtnAgregar;
    private javax.swing.JButton FiltrobtnBusqueda;
    private javax.swing.JTextField FiltrotxtCodigo;
    private javax.swing.JTextField FiltrotxtEstado;
    private javax.swing.JTextField FiltrotxtNombre;
    private javax.swing.JLabel GeneroTitulo;
    private javax.swing.JLabel MantenimientoAlquilada;
    private javax.swing.JLabel MantenimientoCodigoAlquiler;
    private javax.swing.JLabel MantenimientoCodigoPelicula;
    private javax.swing.JLabel MantenimientoEstado;
    private javax.swing.JLabel MantenimientoEstado1;
    private javax.swing.JLabel MantenimientoFechaAlquiler;
    private javax.swing.JButton MantenimientobtnCancelar;
    private javax.swing.JButton MantenimientobtnGuardar;
    private javax.swing.JTextField MantenimientotxtAlquilada;
    private javax.swing.JTextField MantenimientotxtCodigoAlquiler;
    private javax.swing.JTextField MantenimientotxtCodigoPelicula;
    private javax.swing.JTextField MantenimientotxtEstado;
    private javax.swing.JTextField MantenimientotxtFechaAlquiler;
    private javax.swing.JPanel PnlFilter;
    private javax.swing.JPanel PnlMantenimiento;
    private javax.swing.JPanel PnlResultado;
    private javax.swing.JTable ResultadotblLista;
    private javax.swing.JScrollPane ResultadotblListaScrl;
    private javax.swing.JTabbedPane TabControl;
    // End of variables declaration//GEN-END:variables
}
