/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author Programación
 */
public class FrmCliente extends javax.swing.JFrame {

    /**
     * Creates new form FrmGenero
     */
    public FrmCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabControl = new javax.swing.JTabbedPane();
        PnlFilter = new javax.swing.JPanel();
        FiltrobtnBusqueda = new javax.swing.JButton();
        FiltrobtnAgregar = new javax.swing.JButton();
        FiltroCarnet = new javax.swing.JLabel();
        FiltrotxtCarnet1 = new javax.swing.JTextField();
        FiltroNombre = new javax.swing.JLabel();
        FiltrotxtNombre = new javax.swing.JTextField();
        FiltroApellido1 = new javax.swing.JLabel();
        FiltrotxtApellido1 = new javax.swing.JTextField();
        FiltroApellido2 = new javax.swing.JLabel();
        FiltrotxtApellido2 = new javax.swing.JTextField();
        FiltroCedula = new javax.swing.JLabel();
        FiltrotxtCedula = new javax.swing.JTextField();
        FiltroEstado = new javax.swing.JLabel();
        FiltrotxtEstado = new javax.swing.JTextField();
        PnlMantenimiento = new javax.swing.JPanel();
        MantenimientoCarnet = new javax.swing.JLabel();
        MantenimientoNombre = new javax.swing.JLabel();
        MantenimientoDireccion = new javax.swing.JLabel();
        MantenimientoEdad = new javax.swing.JLabel();
        MantenimientoApellido1 = new javax.swing.JLabel();
        MantenimientoApellido2 = new javax.swing.JLabel();
        MantenimientotxtCarnet = new javax.swing.JTextField();
        MantenimientotxtNombre = new javax.swing.JTextField();
        MantenimientotxtDireccion = new javax.swing.JTextField();
        MantenimientotxtEdad = new javax.swing.JTextField();
        MantenimientotxtFechaSalida = new javax.swing.JTextField();
        MantenimientotxtGenero = new javax.swing.JTextField();
        MantenimientobtnGuardar = new javax.swing.JButton();
        MantenimientoTelefono = new javax.swing.JLabel();
        MantenimientotxtTelefono = new javax.swing.JTextField();
        MantenimientoFechaNacimiento = new javax.swing.JLabel();
        MantenimientotxtFechaNacimiento = new javax.swing.JTextField();
        MantenimientoCedula = new javax.swing.JLabel();
        MantenimientotxtCedula = new javax.swing.JTextField();
        MantenimientoFechaIngreso = new javax.swing.JLabel();
        MantenimientotxtFechaIngreso = new javax.swing.JTextField();
        MantenimientoEstado = new javax.swing.JLabel();
        MantenimientotxtEstado = new javax.swing.JTextField();
        PnlResultado = new javax.swing.JPanel();
        ResultadotblListaScrl = new javax.swing.JScrollPane();
        ResultadotblLista = new javax.swing.JTable();
        ClienteTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FiltrobtnBusqueda.setText("Busqueda");

        FiltrobtnAgregar.setText("Agregar");
        FiltrobtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltrobtnAgregarActionPerformed(evt);
            }
        });

        FiltroCarnet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FiltroCarnet.setText("Carnet");

        FiltrotxtCarnet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltrotxtCarnet1ActionPerformed(evt);
            }
        });

        FiltroNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FiltroNombre.setText("Nombre");

        FiltroApellido1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FiltroApellido1.setText("Apellido 1");

        FiltroApellido2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FiltroApellido2.setText("Apellido 2");

        FiltroCedula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FiltroCedula.setText("Cedula");

        FiltroEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FiltroEstado.setText("Estado");

        javax.swing.GroupLayout PnlFilterLayout = new javax.swing.GroupLayout(PnlFilter);
        PnlFilter.setLayout(PnlFilterLayout);
        PnlFilterLayout.setHorizontalGroup(
            PnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFilterLayout.createSequentialGroup()
                .addGroup(PnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PnlFilterLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(FiltroCedula)
                        .addGap(18, 18, 18)
                        .addComponent(FiltrotxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FiltroEstado)
                        .addGap(18, 18, 18)
                        .addComponent(FiltrotxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlFilterLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(PnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PnlFilterLayout.createSequentialGroup()
                                .addComponent(FiltrotxtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(FiltroApellido2)
                                .addGap(18, 18, 18)
                                .addComponent(FiltrotxtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(FiltrobtnBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FiltrobtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(PnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PnlFilterLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(PnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PnlFilterLayout.createSequentialGroup()
                                .addComponent(FiltroCarnet)
                                .addGap(18, 18, 18)
                                .addComponent(FiltrotxtCarnet1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlFilterLayout.createSequentialGroup()
                                .addComponent(FiltroNombre)
                                .addGap(18, 18, 18)
                                .addComponent(FiltrotxtNombre)))
                        .addComponent(FiltroApellido1))
                    .addContainerGap(168, Short.MAX_VALUE)))
        );
        PnlFilterLayout.setVerticalGroup(
            PnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFilterLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(FiltrobtnBusqueda)
                .addGap(17, 17, 17)
                .addComponent(FiltrobtnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FiltrotxtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FiltroApellido2)
                    .addComponent(FiltrotxtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(PnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FiltroCedula)
                    .addComponent(FiltrotxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FiltroEstado)
                    .addComponent(FiltrotxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(PnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PnlFilterLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addGroup(PnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FiltroCarnet)
                        .addComponent(FiltrotxtCarnet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(PnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FiltroNombre)
                        .addComponent(FiltrotxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(FiltroApellido1)
                    .addContainerGap(187, Short.MAX_VALUE)))
        );

        TabControl.addTab("Filtro", PnlFilter);

        PnlMantenimiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        MantenimientoCarnet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MantenimientoCarnet.setText("Carnet");

        MantenimientoNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MantenimientoNombre.setText("Nombre");

        MantenimientoDireccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MantenimientoDireccion.setText("Direccion");

        MantenimientoEdad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MantenimientoEdad.setText("Edad");

        MantenimientoApellido1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MantenimientoApellido1.setText("Apellido 1");

        MantenimientoApellido2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MantenimientoApellido2.setText("Apellido 2");

        MantenimientotxtCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantenimientotxtCarnetActionPerformed(evt);
            }
        });

        MantenimientobtnGuardar.setText("Guardar");

        MantenimientoTelefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MantenimientoTelefono.setText("Telefono");

        MantenimientoFechaNacimiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MantenimientoFechaNacimiento.setText("Fecha de nacimiento");

        MantenimientoCedula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MantenimientoCedula.setText("Cedula");

        MantenimientoFechaIngreso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MantenimientoFechaIngreso.setText("Fecha de Ingreso");

        MantenimientoEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MantenimientoEstado.setText("Estado");

        javax.swing.GroupLayout PnlMantenimientoLayout = new javax.swing.GroupLayout(PnlMantenimiento);
        PnlMantenimiento.setLayout(PnlMantenimientoLayout);
        PnlMantenimientoLayout.setHorizontalGroup(
            PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlMantenimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlMantenimientoLayout.createSequentialGroup()
                        .addGroup(PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PnlMantenimientoLayout.createSequentialGroup()
                                .addComponent(MantenimientoCarnet)
                                .addGap(18, 18, 18)
                                .addComponent(MantenimientotxtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlMantenimientoLayout.createSequentialGroup()
                                .addComponent(MantenimientoNombre)
                                .addGap(18, 18, 18)
                                .addComponent(MantenimientotxtNombre)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MantenimientobtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(PnlMantenimientoLayout.createSequentialGroup()
                        .addGroup(PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PnlMantenimientoLayout.createSequentialGroup()
                                .addComponent(MantenimientoDireccion)
                                .addGap(18, 18, 18)
                                .addComponent(MantenimientotxtDireccion))
                            .addGroup(PnlMantenimientoLayout.createSequentialGroup()
                                .addComponent(MantenimientoApellido1)
                                .addGap(18, 18, 18)
                                .addComponent(MantenimientotxtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(MantenimientoApellido2)
                                .addGap(18, 18, 18)
                                .addComponent(MantenimientotxtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PnlMantenimientoLayout.createSequentialGroup()
                                .addGroup(PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PnlMantenimientoLayout.createSequentialGroup()
                                        .addComponent(MantenimientoEdad)
                                        .addGap(18, 18, 18)
                                        .addComponent(MantenimientotxtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PnlMantenimientoLayout.createSequentialGroup()
                                        .addComponent(MantenimientoFechaNacimiento)
                                        .addGap(18, 18, 18)
                                        .addComponent(MantenimientotxtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PnlMantenimientoLayout.createSequentialGroup()
                                        .addComponent(MantenimientoTelefono)
                                        .addGap(18, 18, 18)
                                        .addComponent(MantenimientotxtTelefono))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlMantenimientoLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(PnlMantenimientoLayout.createSequentialGroup()
                                                .addComponent(MantenimientoEstado)
                                                .addGap(18, 18, 18)
                                                .addComponent(MantenimientotxtEstado))
                                            .addGroup(PnlMantenimientoLayout.createSequentialGroup()
                                                .addComponent(MantenimientoCedula)
                                                .addGap(18, 18, 18)
                                                .addComponent(MantenimientotxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addContainerGap(36, Short.MAX_VALUE))
                    .addGroup(PnlMantenimientoLayout.createSequentialGroup()
                        .addComponent(MantenimientoFechaIngreso)
                        .addGap(18, 18, 18)
                        .addComponent(MantenimientotxtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PnlMantenimientoLayout.setVerticalGroup(
            PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlMantenimientoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MantenimientoCarnet)
                    .addComponent(MantenimientotxtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MantenimientobtnGuardar))
                .addGap(18, 18, 18)
                .addGroup(PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MantenimientoNombre)
                    .addComponent(MantenimientotxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MantenimientoApellido1)
                    .addComponent(MantenimientotxtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MantenimientoApellido2)
                    .addComponent(MantenimientotxtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MantenimientoDireccion)
                    .addComponent(MantenimientotxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MantenimientoEdad)
                    .addComponent(MantenimientotxtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MantenimientoTelefono)
                    .addComponent(MantenimientotxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MantenimientoFechaNacimiento)
                    .addComponent(MantenimientotxtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MantenimientoCedula)
                    .addComponent(MantenimientotxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MantenimientoFechaIngreso)
                    .addComponent(MantenimientotxtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MantenimientoEstado)
                        .addComponent(MantenimientotxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        TabControl.addTab("Mantenimiento", PnlMantenimiento);

        ResultadotblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ResultadotblListaScrl.setViewportView(ResultadotblLista);

        javax.swing.GroupLayout PnlResultadoLayout = new javax.swing.GroupLayout(PnlResultado);
        PnlResultado.setLayout(PnlResultadoLayout);
        PnlResultadoLayout.setHorizontalGroup(
            PnlResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ResultadotblListaScrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        PnlResultadoLayout.setVerticalGroup(
            PnlResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlResultadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ResultadotblListaScrl, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        TabControl.addTab("Resultado", PnlResultado);

        ClienteTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ClienteTitulo.setText("Mantenimiento Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TabControl, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClienteTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ClienteTitulo)
                .addGap(18, 18, 18)
                .addComponent(TabControl)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MantenimientotxtCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantenimientotxtCarnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MantenimientotxtCarnetActionPerformed

    private void FiltrobtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltrobtnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FiltrobtnAgregarActionPerformed

    private void FiltrotxtCarnet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltrotxtCarnet1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FiltrotxtCarnet1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClienteTitulo;
    private javax.swing.JLabel FiltroApellido1;
    private javax.swing.JLabel FiltroApellido2;
    private javax.swing.JLabel FiltroCarnet;
    private javax.swing.JLabel FiltroCedula;
    private javax.swing.JLabel FiltroEstado;
    private javax.swing.JLabel FiltroNombre;
    private javax.swing.JButton FiltrobtnAgregar;
    private javax.swing.JButton FiltrobtnBusqueda;
    private javax.swing.JTextField FiltrotxtApellido1;
    private javax.swing.JTextField FiltrotxtApellido2;
    private javax.swing.JTextField FiltrotxtCarnet1;
    private javax.swing.JTextField FiltrotxtCedula;
    private javax.swing.JTextField FiltrotxtEstado;
    private javax.swing.JTextField FiltrotxtNombre;
    private javax.swing.JLabel MantenimientoApellido1;
    private javax.swing.JLabel MantenimientoApellido2;
    private javax.swing.JLabel MantenimientoCarnet;
    private javax.swing.JLabel MantenimientoCedula;
    private javax.swing.JLabel MantenimientoDireccion;
    private javax.swing.JLabel MantenimientoEdad;
    private javax.swing.JLabel MantenimientoEstado;
    private javax.swing.JLabel MantenimientoFechaIngreso;
    private javax.swing.JLabel MantenimientoFechaNacimiento;
    private javax.swing.JLabel MantenimientoNombre;
    private javax.swing.JLabel MantenimientoTelefono;
    private javax.swing.JButton MantenimientobtnGuardar;
    private javax.swing.JTextField MantenimientotxtCarnet;
    private javax.swing.JTextField MantenimientotxtCedula;
    private javax.swing.JTextField MantenimientotxtDireccion;
    private javax.swing.JTextField MantenimientotxtEdad;
    private javax.swing.JTextField MantenimientotxtEstado;
    private javax.swing.JTextField MantenimientotxtFechaIngreso;
    private javax.swing.JTextField MantenimientotxtFechaNacimiento;
    private javax.swing.JTextField MantenimientotxtFechaSalida;
    private javax.swing.JTextField MantenimientotxtGenero;
    private javax.swing.JTextField MantenimientotxtNombre;
    private javax.swing.JTextField MantenimientotxtTelefono;
    private javax.swing.JPanel PnlFilter;
    private javax.swing.JPanel PnlMantenimiento;
    private javax.swing.JPanel PnlResultado;
    private javax.swing.JTable ResultadotblLista;
    private javax.swing.JScrollPane ResultadotblListaScrl;
    private javax.swing.JTabbedPane TabControl;
    // End of variables declaration//GEN-END:variables
}
