/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentaciones;

import javax.swing.JOptionPane;

/**
 *
 * @author leungure
 */
public class FrmPrincipal extends javax.swing.JFrame {

    FrmZona FormularioZonas = new FrmZona();
    FrmHabitat FormularioHabitats = new FrmHabitat();
    FrmItinerario FormularioItinerario = new FrmItinerario ();
    FrmEspecie FormularioEspecies = new FrmEspecie ();
    FrmGuia FormularioGuias = new FrmGuia ();
    FrmCuidador FormularioCuidadores = new FrmCuidador ();
    
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Zonas = new javax.swing.JButton();
        Habitats = new javax.swing.JButton();
        Itinerarios = new javax.swing.JButton();
        Especies = new javax.swing.JButton();
        Guias = new javax.swing.JButton();
        Cuidadores = new javax.swing.JButton();
        TituloHeader = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simon Bolivar");

        Zonas.setText("Zonas");
        Zonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ZonasMouseClicked(evt);
            }
        });

        Habitats.setText("Habitats");
        Habitats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HabitatsMouseClicked(evt);
            }
        });

        Itinerarios.setText("Itinerarios");
        Itinerarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItinerariosMouseClicked(evt);
            }
        });

        Especies.setText("Especies");
        Especies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EspeciesMouseClicked(evt);
            }
        });

        Guias.setText("Guias");
        Guias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuiasMouseClicked(evt);
            }
        });

        Cuidadores.setText("Cuidadores");
        Cuidadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CuidadoresMouseClicked(evt);
            }
        });

        TituloHeader.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TituloHeader.setText("Sistema de Manejo de Zoologico");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Habitats, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Especies, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Cuidadores, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Zonas, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Itinerarios, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Guias, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(TituloHeader)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(TituloHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Zonas)
                    .addComponent(Guias)
                    .addComponent(Itinerarios))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Habitats)
                    .addComponent(Cuidadores)
                    .addComponent(Especies))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ZonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZonasMouseClicked
        FormularioZonas.setVisible(true);
        FormularioHabitats.setVisible(false);
    }//GEN-LAST:event_ZonasMouseClicked

    private void HabitatsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HabitatsMouseClicked
        FormularioHabitats.setVisible(true);
        FormularioZonas.setVisible(false);
    }//GEN-LAST:event_HabitatsMouseClicked

    private void ItinerariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItinerariosMouseClicked
        FormularioItinerario.setVisible(true);
        FormularioZonas.setVisible(false);
    }//GEN-LAST:event_ItinerariosMouseClicked

    private void EspeciesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EspeciesMouseClicked
        FormularioEspecies.setVisible(true);
        FormularioZonas.setVisible(false);
    }//GEN-LAST:event_EspeciesMouseClicked

    private void GuiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuiasMouseClicked
        FormularioGuias.setVisible(true);
        FormularioZonas.setVisible(false);
    }//GEN-LAST:event_GuiasMouseClicked

    private void CuidadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CuidadoresMouseClicked
        FormularioCuidadores.setVisible(true);
        FormularioZonas.setVisible(false);
    }//GEN-LAST:event_CuidadoresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cuidadores;
    private javax.swing.JButton Especies;
    private javax.swing.JButton Guias;
    private javax.swing.JButton Habitats;
    private javax.swing.JButton Itinerarios;
    private javax.swing.JLabel TituloHeader;
    private javax.swing.JButton Zonas;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
